### ISSUE TITLE
Erro com versão 9.2.4

### ISSUE THREAD

**Issue by zezao123** [JulioAugustoS/glpiorderservice#20]
Amigo Julio, muito bom seu plugin, porem está dando este erro com a versão 9.2.4, assim que clico na aba Imprimir OS no ticket ele gera o seguinte:

_Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/glpi/inc/dbmysql.class.php:312 Stack trace: #0 /var/www/html/glpi/plugins/orderservice/inc/common.class.php(103): DBmysql->fetch_assoc(false) #1 /var/www/html/glpi/plugins/orderservice/inc/orderservice.class.php(49): CommonOrderService::configPlugin() #2 /var/www/html/glpi/plugins/orderservice/setup.php(80): PluginOrderService->printOsTicketOpen('25122', 2) #3 /var/www/html/glpi/plugins/orderservice/setup.php(111): PluginOrderServiceConfig::showForTicket(Object(Ticket)) #4 /var/www/html/glpi/inc/commonglpi.class.php(482): PluginOrderServiceConfig::displayTabContentForItem(Object(Ticket), '1', '') #5 /var/www/html/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Ticket), 'PluginOrderServ...', '', Array) #6 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 312_

![image](https://user-images.githubusercontent.com/37622166/52210152-4a068b80-286d-11e9-80a3-a9df1dc342a6.png)

**Comment by JulioAugustoS** [comment]
Olá amigo, obrigado.
vou fazer um teste nessa versão que vc está usando e te dou um retorno.
